export * from './Header/Header.component'
export * from './Main/Main.component'
export * from './Footer/Footer.component'
export * from './Slogan/Slogan.component'
export * from './Sobre/Sobre.component'
export * from './Portifolio/Portifolio.component'
export * from './Projeto/Projeto.component'
export * from './Contato/Contato.component'
