import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Header, Main, Footer } from '../components'
import axios from 'axios'

export default function Home({ projetos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>LJA Software</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Main projetos={projetos} />
      <Footer />
    </div>
  )
}

export async function getServerSideProps(context) {
  const urlAtual = context.req.headers.host
  const resposta = await axios.get(`http://${urlAtual}/api/projetos`)
  const projetos = resposta.data.projetos

  return { props: { projetos } }
}
